name: cap_challenge
description: Cap Challenge - school project.

dependencies:
  flutter:
    sdk: flutter
#  qrcode_reader: "0.3.3"
  google_sign_in: "^3.0.3"
  firebase_auth: "^0.5.10"
  firebase_database: "^1.0.0"
  cupertino_icons: ^0.1.0
  flutter_facebook_login: "^1.1.1"
  sliver_fab: "^0.1.0"
  sensors: "^0.3.2"


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/cap.png
    - images/qr_code.png
    - images/sign-in-facebook.png
    - images/sign-in-google.png
    - images/coca_family.png
    - images/bottle_empty.png
    - images/bottle_filled.png
    - images/coca_cola/can.png
    - images/coca_cola/bottle_small.png
    - images/coca_cola/bottle_big.png
    - images/fanta/can.png
    - images/fanta/bottle_small.png
    - images/fanta/bottle_big.png
    - images/sprite/can.png
    - images/sprite/bottle_small.png
    - images/sprite/bottle_medium.png
    - images/sprite/bottle_big.png
    - images/coca_cola_baner.jpg
    - images/coke_light.png
    - images/coke_zero.png
    - images/fanta_baner.jpg
    - images/sprite_baner.jpeg
    - images/bubbles.jpg
    - images/bubbles_long.jpg
    - images/challenge_bottle.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
